services:
  dashboard:
    image: ghcr.io/consolecmnd/dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - WEATHERAPI_KEY=${WEATHERAPI_KEY:-}
      - WEATHER_LOCATION=${WEATHER_LOCATION:-}
